
PRINT 'Adding Nominal Pages...'

INSERT INTO [dbo].[tblPage]([PageName], [PageIndex], [ShortTitleTextItem], [LongTitleTextItem], [NavStripTextItem], [PageURL], [PageNotes], [HelpTextItem], [HelpWindowTop], [HelpWindowLeft], [HelpWindowHeight], [HelpWindowWidth], [MenuItemIndex], [HelpHtmlSource], [HelpVideoUri])
SELECT GLP.[PageName], GLP.[PageIndex], GLP.[ShortTitleTextItem], GLP.[LongTitleTextItem], GLP.[NavStripTextItem], GLP.[PageURL], GLP.[PageNotes], GLP.[HelpTextItem], GLP.[HelpWindowTop], GLP.[HelpWindowLeft], GLP.[HelpWindowHeight], GLP.[HelpWindowWidth], GLP.[MenuItemIndex], GLP.[HelpHtmlSource], GLP.[HelpVideoUri]
FROM
(
SELECT N'_BankRec' as [PageName], 20000 as [PageIndex], NULL as [ShortTitleTextItem], NULL as [LongTitleTextItem], NULL as [NavStripTextItem], NULL as [PageURL], NULL as [PageNotes], NULL as [HelpTextItem], NULL as [HelpWindowTop], NULL as [HelpWindowLeft], NULL as [HelpWindowHeight], NULL as [HelpWindowWidth], 0 as [MenuItemIndex], NULL as [HelpHtmlSource], NULL as [HelpVideoUri] UNION ALL
SELECT N'_BankRecPost', 20000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL UNION ALL
SELECT N'_CostingUpdate', 20000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL UNION ALL
SELECT N'_CreateDisbursements', 20000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 700, 880, 0, NULL, NULL UNION ALL
SELECT N'_CreateJournal', 20000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 700, 880, 0, NULL, NULL UNION ALL
SELECT N'_DisbMap', 20000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL UNION ALL
SELECT N'_DisbMapDetail', 20000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL UNION ALL
SELECT N'_ExportAccountMap', 20000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 700, 880, 0, NULL, NULL UNION ALL
SELECT N'_ImportAccountMap', 20000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 700, 880, 0, NULL, NULL UNION ALL
SELECT N'_Integrationdetails', 20000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 800, 960, 0, NULL, NULL UNION ALL
SELECT N'_IntegrationExtract', 20000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 300, 450, 0, NULL, NULL UNION ALL
SELECT N'_IntegrationSetup', 20000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 700, 880, 0, NULL, NULL UNION ALL
SELECT N'_Journal', 20000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL UNION ALL
SELECT N'_MapDetail', 20000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL UNION ALL
SELECT N'_MissingMap', 20000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL UNION ALL
SELECT N'_MissingMappings', 20000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 700, 880, 0, NULL, NULL UNION ALL
SELECT N'_NLImport', 20000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL UNION ALL
SELECT N'_NLMap', 20000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL UNION ALL
SELECT N'_NominalControl', 20000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL UNION ALL
SELECT N'_OrganisationDetails', 20000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL UNION ALL
SELECT N'_Organisations', 20000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 700, 880, 0, NULL, NULL UNION ALL
SELECT N'_PostCreate', 20000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL UNION ALL
SELECT N'_Posting', 20000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 700, 880, 0, NULL, NULL UNION ALL
SELECT N'_RepostJournal', 20000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 700, 880, 0, NULL, NULL UNION ALL
SELECT N'_ReprintJournal', 20000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 700, 880, 0, NULL, NULL UNION ALL
SELECT N'_ReprintJournalDetails', 20000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 700, 880, 0, NULL, NULL UNION ALL
SELECT N'_RetransferCashbook', 20000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 700, 880, 0, NULL, NULL UNION ALL
SELECT N'_UpdateBankRec', 20000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 700, 880, 0, NULL, NULL UNION ALL
SELECT N'_UpdateCosting', 20000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 700, 880, 0, NULL, NULL UNION ALL
SELECT N'_ExpPosting', 20000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 700, 880, 0, NULL, NULL UNION ALL
SELECT N'_IntacctSync', 20000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 700, 880, 0, NULL, NULL
) GLP
LEFT OUTER JOIN tblPage P ON GLP.[PageName] = P.[PageName]
WHERE P.[PageName] IS NULL

PRINT 'Granting Access to Nominal Pages for Administrator Group...'

INSERT INTO tblPageAccess(Page, StaffIndex, GroupIndex, AccessLevel)
SELECT T.[PageName], 0, 1, 1
FROM (
	SELECT P.[PageName]
	FROM tblPage P
	LEFT OUTER JOIN tblPageAccess PA ON P.[PageName] = PA.[Page]
	WHERE P.[PageName] Like '!_%' ESCAPE '!' AND PA.[Page] IS NULL
) T