//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepGen96
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.praceng.com/webservices/perepgen", ConfigurationName="RepGen96.PERepGenSoap")]
    public interface PERepGenSoap
    {
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/GenerateFee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<RepGen96.GenerateFeeResponse> GenerateFeeAsync(RepGen96.GenerateFeeRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/GenerateStatement", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<RepGen96.GenerateStatementResponse> GenerateStatementAsync(RepGen96.GenerateStatementRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/GenerateExpenseReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<RepGen96.GenerateExpenseReportResponse> GenerateExpenseReportAsync(RepGen96.GenerateExpenseReportRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/GenerateAndStoreReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<RepGen96.GenerateAndStoreReportResponse> GenerateAndStoreReportAsync(RepGen96.GenerateAndStoreReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/GetThumbnailForReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<RepGen96.GetThumbnailForReportResponse> GetThumbnailForReportAsync(RepGen96.GetThumbnailForReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/ExportReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<RepGen96.ExportReportResponse> ExportReportAsync(RepGen96.ExportReportRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/GenerateReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<RepGen96.GenerateReportResponse> GenerateReportAsync(RepGen96.GenerateReportRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/GenerateReportToPDF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<RepGen96.GenerateReportToPDFResponse> GenerateReportToPDFAsync(RepGen96.GenerateReportToPDFRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/GenerateReportToPDFv9", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<RepGen96.GenerateReportToPDFv9Response> GenerateReportToPDFv9Async(RepGen96.GenerateReportToPDFv9Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/ExportToExcel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<RepGen96.ExportToExcelResponse> ExportToExcelAsync(RepGen96.ExportToExcelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/ExportToExcelWithRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<RepGen96.ExportToExcelWithRangeResponse> ExportToExcelWithRangeAsync(RepGen96.ExportToExcelWithRangeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/ExportToPDF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<RepGen96.ExportToPDFResponse> ExportToPDFAsync(RepGen96.ExportToPDFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/ExportToPDFWithRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<RepGen96.ExportToPDFWithRangeResponse> ExportToPDFWithRangeAsync(RepGen96.ExportToPDFWithRangeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/ExportToWord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<RepGen96.ExportToWordResponse> ExportToWordAsync(RepGen96.ExportToWordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/ExportToWordWithRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<RepGen96.ExportToWordWithRangeResponse> ExportToWordWithRangeAsync(RepGen96.ExportToWordWithRangeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/ExportToTiff", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<RepGen96.ExportToTiffResponse> ExportToTiffAsync(RepGen96.ExportToTiffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/ExportToTiffWithRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<RepGen96.ExportToTiffWithRangeResponse> ExportToTiffWithRangeAsync(RepGen96.ExportToTiffWithRangeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/ExportToTxt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<RepGen96.ExportToTxtResponse> ExportToTxtAsync(RepGen96.ExportToTxtRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/ExportToTxtWithRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<RepGen96.ExportToTxtWithRangeResponse> ExportToTxtWithRangeAsync(RepGen96.ExportToTxtWithRangeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/PrintGrid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<RepGen96.PrintGridResponse> PrintGridAsync(RepGen96.PrintGridRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/TestMethod", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<string> TestMethodAsync(string Paramater);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/UploadReportLayouts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<string> UploadReportLayoutsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/DownloadReportLayouts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<string> DownloadReportLayoutsAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.praceng.com/webservices/perepgen")]
    public partial class AuthenticationInformation
    {
        
        private string authorizationField;
        
        private string userNameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Authorization
        {
            get
            {
                return this.authorizationField;
            }
            set
            {
                this.authorizationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateFee", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class GenerateFeeRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.praceng.com/webservices/perepgen")]
        public RepGen96.AuthenticationInformation AuthenticationInformation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        public int DebtTranIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public int Format;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=2)]
        public int StaffId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=3)]
        public string Error;
        
        public GenerateFeeRequest()
        {
        }
        
        public GenerateFeeRequest(RepGen96.AuthenticationInformation AuthenticationInformation, int DebtTranIndex, int Format, int StaffId, string Error)
        {
            this.AuthenticationInformation = AuthenticationInformation;
            this.DebtTranIndex = DebtTranIndex;
            this.Format = Format;
            this.StaffId = StaffId;
            this.Error = Error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateFeeResponse", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class GenerateFeeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GenerateFeeResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public string Error;
        
        public GenerateFeeResponse()
        {
        }
        
        public GenerateFeeResponse(byte[] GenerateFeeResult, string Error)
        {
            this.GenerateFeeResult = GenerateFeeResult;
            this.Error = Error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateStatement", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class GenerateStatementRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.praceng.com/webservices/perepgen")]
        public RepGen96.AuthenticationInformation AuthenticationInformation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        public int ContIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public int Format;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=2)]
        public bool IncludeFees;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=3)]
        public int StaffId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=4)]
        public string Error;
        
        public GenerateStatementRequest()
        {
        }
        
        public GenerateStatementRequest(RepGen96.AuthenticationInformation AuthenticationInformation, int ContIndex, int Format, bool IncludeFees, int StaffId, string Error)
        {
            this.AuthenticationInformation = AuthenticationInformation;
            this.ContIndex = ContIndex;
            this.Format = Format;
            this.IncludeFees = IncludeFees;
            this.StaffId = StaffId;
            this.Error = Error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateStatementResponse", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class GenerateStatementResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GenerateStatementResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public string Error;
        
        public GenerateStatementResponse()
        {
        }
        
        public GenerateStatementResponse(byte[] GenerateStatementResult, string Error)
        {
            this.GenerateStatementResult = GenerateStatementResult;
            this.Error = Error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateExpenseReport", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class GenerateExpenseReportRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.praceng.com/webservices/perepgen")]
        public RepGen96.AuthenticationInformation AuthenticationInformation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        public int ExpIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public int StaffId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=2)]
        public string Error;
        
        public GenerateExpenseReportRequest()
        {
        }
        
        public GenerateExpenseReportRequest(RepGen96.AuthenticationInformation AuthenticationInformation, int ExpIndex, int StaffId, string Error)
        {
            this.AuthenticationInformation = AuthenticationInformation;
            this.ExpIndex = ExpIndex;
            this.StaffId = StaffId;
            this.Error = Error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateExpenseReportResponse", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class GenerateExpenseReportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GenerateExpenseReportResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public string Error;
        
        public GenerateExpenseReportResponse()
        {
        }
        
        public GenerateExpenseReportResponse(byte[] GenerateExpenseReportResult, string Error)
        {
            this.GenerateExpenseReportResult = GenerateExpenseReportResult;
            this.Error = Error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateAndStoreReport", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class GenerateAndStoreReportRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.praceng.com/webservices/perepgen")]
        public RepGen96.AuthenticationInformation AuthenticationInformation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        public string ReportID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public object[] Params;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=2)]
        public string StaffName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=3)]
        public string StaffId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=4)]
        public bool ErrorOnNoData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=5)]
        public string Error;
        
        public GenerateAndStoreReportRequest()
        {
        }
        
        public GenerateAndStoreReportRequest(RepGen96.AuthenticationInformation AuthenticationInformation, string ReportID, object[] Params, string StaffName, string StaffId, bool ErrorOnNoData, string Error)
        {
            this.AuthenticationInformation = AuthenticationInformation;
            this.ReportID = ReportID;
            this.Params = Params;
            this.StaffName = StaffName;
            this.StaffId = StaffId;
            this.ErrorOnNoData = ErrorOnNoData;
            this.Error = Error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateAndStoreReportResponse", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class GenerateAndStoreReportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        public System.Guid GenerateAndStoreReportResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public string Error;
        
        public GenerateAndStoreReportResponse()
        {
        }
        
        public GenerateAndStoreReportResponse(System.Guid GenerateAndStoreReportResult, string Error)
        {
            this.GenerateAndStoreReportResult = GenerateAndStoreReportResult;
            this.Error = Error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetThumbnailForReport", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class GetThumbnailForReportRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.praceng.com/webservices/perepgen")]
        public RepGen96.AuthenticationInformation AuthenticationInformation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        public System.Guid fileID;
        
        public GetThumbnailForReportRequest()
        {
        }
        
        public GetThumbnailForReportRequest(RepGen96.AuthenticationInformation AuthenticationInformation, System.Guid fileID)
        {
            this.AuthenticationInformation = AuthenticationInformation;
            this.fileID = fileID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetThumbnailForReportResponse", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class GetThumbnailForReportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        public string GetThumbnailForReportResult;
        
        public GetThumbnailForReportResponse()
        {
        }
        
        public GetThumbnailForReportResponse(string GetThumbnailForReportResult)
        {
            this.GetThumbnailForReportResult = GetThumbnailForReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportReport", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportReportRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.praceng.com/webservices/perepgen")]
        public RepGen96.AuthenticationInformation AuthenticationInformation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        public System.Guid fileID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public string exportType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=2)]
        public int firstPage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=3)]
        public int lastPage;
        
        public ExportReportRequest()
        {
        }
        
        public ExportReportRequest(RepGen96.AuthenticationInformation AuthenticationInformation, System.Guid fileID, string exportType, int firstPage, int lastPage)
        {
            this.AuthenticationInformation = AuthenticationInformation;
            this.fileID = fileID;
            this.exportType = exportType;
            this.firstPage = firstPage;
            this.lastPage = lastPage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportReportResponse", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportReportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        public int ExportReportResult;
        
        public ExportReportResponse()
        {
        }
        
        public ExportReportResponse(int ExportReportResult)
        {
            this.ExportReportResult = ExportReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateReport", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class GenerateReportRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.praceng.com/webservices/perepgen")]
        public RepGen96.AuthenticationInformation AuthenticationInformation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        public string ReportID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public object[] Params;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=2)]
        public string StaffName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=3)]
        public string StaffId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=4)]
        public bool ErrorOnNoData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=5)]
        public string Error;
        
        public GenerateReportRequest()
        {
        }
        
        public GenerateReportRequest(RepGen96.AuthenticationInformation AuthenticationInformation, string ReportID, object[] Params, string StaffName, string StaffId, bool ErrorOnNoData, string Error)
        {
            this.AuthenticationInformation = AuthenticationInformation;
            this.ReportID = ReportID;
            this.Params = Params;
            this.StaffName = StaffName;
            this.StaffId = StaffId;
            this.ErrorOnNoData = ErrorOnNoData;
            this.Error = Error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateReportResponse", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class GenerateReportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GenerateReportResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public string Error;
        
        public GenerateReportResponse()
        {
        }
        
        public GenerateReportResponse(byte[] GenerateReportResult, string Error)
        {
            this.GenerateReportResult = GenerateReportResult;
            this.Error = Error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateReportToPDF", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class GenerateReportToPDFRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.praceng.com/webservices/perepgen")]
        public RepGen96.AuthenticationInformation AuthenticationInformation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        public string ReportID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public object[] Params;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=2)]
        public string StaffName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=3)]
        public string StaffId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=4)]
        public bool ErrorOnNoData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=5)]
        public string Error;
        
        public GenerateReportToPDFRequest()
        {
        }
        
        public GenerateReportToPDFRequest(RepGen96.AuthenticationInformation AuthenticationInformation, string ReportID, object[] Params, string StaffName, string StaffId, bool ErrorOnNoData, string Error)
        {
            this.AuthenticationInformation = AuthenticationInformation;
            this.ReportID = ReportID;
            this.Params = Params;
            this.StaffName = StaffName;
            this.StaffId = StaffId;
            this.ErrorOnNoData = ErrorOnNoData;
            this.Error = Error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateReportToPDFResponse", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class GenerateReportToPDFResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GenerateReportToPDFResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public string Error;
        
        public GenerateReportToPDFResponse()
        {
        }
        
        public GenerateReportToPDFResponse(byte[] GenerateReportToPDFResult, string Error)
        {
            this.GenerateReportToPDFResult = GenerateReportToPDFResult;
            this.Error = Error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateReportToPDFv9", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class GenerateReportToPDFv9Request
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.praceng.com/webservices/perepgen")]
        public RepGen96.AuthenticationInformation AuthenticationInformation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        public string ReportID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public object[] Params;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=2)]
        public string StaffName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=3)]
        public string StaffId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=4)]
        public bool ErrorOnNoData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=5)]
        public string Error;
        
        public GenerateReportToPDFv9Request()
        {
        }
        
        public GenerateReportToPDFv9Request(RepGen96.AuthenticationInformation AuthenticationInformation, string ReportID, object[] Params, string StaffName, string StaffId, bool ErrorOnNoData, string Error)
        {
            this.AuthenticationInformation = AuthenticationInformation;
            this.ReportID = ReportID;
            this.Params = Params;
            this.StaffName = StaffName;
            this.StaffId = StaffId;
            this.ErrorOnNoData = ErrorOnNoData;
            this.Error = Error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateReportToPDFv9Response", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class GenerateReportToPDFv9Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GenerateReportToPDFv9Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public string Error;
        
        public GenerateReportToPDFv9Response()
        {
        }
        
        public GenerateReportToPDFv9Response(byte[] GenerateReportToPDFv9Result, string Error)
        {
            this.GenerateReportToPDFv9Result = GenerateReportToPDFv9Result;
            this.Error = Error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToExcel", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToExcelRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.praceng.com/webservices/perepgen")]
        public RepGen96.AuthenticationInformation AuthenticationInformation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] doc;
        
        public ExportToExcelRequest()
        {
        }
        
        public ExportToExcelRequest(RepGen96.AuthenticationInformation AuthenticationInformation, byte[] doc)
        {
            this.AuthenticationInformation = AuthenticationInformation;
            this.doc = doc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToExcelResponse", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToExcelResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ExportToExcelResult;
        
        public ExportToExcelResponse()
        {
        }
        
        public ExportToExcelResponse(byte[] ExportToExcelResult)
        {
            this.ExportToExcelResult = ExportToExcelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToExcelWithRange", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToExcelWithRangeRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.praceng.com/webservices/perepgen")]
        public RepGen96.AuthenticationInformation AuthenticationInformation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] doc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public string PageRange;
        
        public ExportToExcelWithRangeRequest()
        {
        }
        
        public ExportToExcelWithRangeRequest(RepGen96.AuthenticationInformation AuthenticationInformation, byte[] doc, string PageRange)
        {
            this.AuthenticationInformation = AuthenticationInformation;
            this.doc = doc;
            this.PageRange = PageRange;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToExcelWithRangeResponse", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToExcelWithRangeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ExportToExcelWithRangeResult;
        
        public ExportToExcelWithRangeResponse()
        {
        }
        
        public ExportToExcelWithRangeResponse(byte[] ExportToExcelWithRangeResult)
        {
            this.ExportToExcelWithRangeResult = ExportToExcelWithRangeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToPDF", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToPDFRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.praceng.com/webservices/perepgen")]
        public RepGen96.AuthenticationInformation AuthenticationInformation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] doc;
        
        public ExportToPDFRequest()
        {
        }
        
        public ExportToPDFRequest(RepGen96.AuthenticationInformation AuthenticationInformation, byte[] doc)
        {
            this.AuthenticationInformation = AuthenticationInformation;
            this.doc = doc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToPDFResponse", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToPDFResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ExportToPDFResult;
        
        public ExportToPDFResponse()
        {
        }
        
        public ExportToPDFResponse(byte[] ExportToPDFResult)
        {
            this.ExportToPDFResult = ExportToPDFResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToPDFWithRange", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToPDFWithRangeRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.praceng.com/webservices/perepgen")]
        public RepGen96.AuthenticationInformation AuthenticationInformation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] doc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public string PageRange;
        
        public ExportToPDFWithRangeRequest()
        {
        }
        
        public ExportToPDFWithRangeRequest(RepGen96.AuthenticationInformation AuthenticationInformation, byte[] doc, string PageRange)
        {
            this.AuthenticationInformation = AuthenticationInformation;
            this.doc = doc;
            this.PageRange = PageRange;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToPDFWithRangeResponse", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToPDFWithRangeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ExportToPDFWithRangeResult;
        
        public ExportToPDFWithRangeResponse()
        {
        }
        
        public ExportToPDFWithRangeResponse(byte[] ExportToPDFWithRangeResult)
        {
            this.ExportToPDFWithRangeResult = ExportToPDFWithRangeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToWord", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToWordRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.praceng.com/webservices/perepgen")]
        public RepGen96.AuthenticationInformation AuthenticationInformation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] doc;
        
        public ExportToWordRequest()
        {
        }
        
        public ExportToWordRequest(RepGen96.AuthenticationInformation AuthenticationInformation, byte[] doc)
        {
            this.AuthenticationInformation = AuthenticationInformation;
            this.doc = doc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToWordResponse", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToWordResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ExportToWordResult;
        
        public ExportToWordResponse()
        {
        }
        
        public ExportToWordResponse(byte[] ExportToWordResult)
        {
            this.ExportToWordResult = ExportToWordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToWordWithRange", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToWordWithRangeRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.praceng.com/webservices/perepgen")]
        public RepGen96.AuthenticationInformation AuthenticationInformation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] doc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public string PageRange;
        
        public ExportToWordWithRangeRequest()
        {
        }
        
        public ExportToWordWithRangeRequest(RepGen96.AuthenticationInformation AuthenticationInformation, byte[] doc, string PageRange)
        {
            this.AuthenticationInformation = AuthenticationInformation;
            this.doc = doc;
            this.PageRange = PageRange;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToWordWithRangeResponse", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToWordWithRangeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ExportToWordWithRangeResult;
        
        public ExportToWordWithRangeResponse()
        {
        }
        
        public ExportToWordWithRangeResponse(byte[] ExportToWordWithRangeResult)
        {
            this.ExportToWordWithRangeResult = ExportToWordWithRangeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToTiff", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToTiffRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.praceng.com/webservices/perepgen")]
        public RepGen96.AuthenticationInformation AuthenticationInformation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] doc;
        
        public ExportToTiffRequest()
        {
        }
        
        public ExportToTiffRequest(RepGen96.AuthenticationInformation AuthenticationInformation, byte[] doc)
        {
            this.AuthenticationInformation = AuthenticationInformation;
            this.doc = doc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToTiffResponse", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToTiffResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ExportToTiffResult;
        
        public ExportToTiffResponse()
        {
        }
        
        public ExportToTiffResponse(byte[] ExportToTiffResult)
        {
            this.ExportToTiffResult = ExportToTiffResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToTiffWithRange", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToTiffWithRangeRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.praceng.com/webservices/perepgen")]
        public RepGen96.AuthenticationInformation AuthenticationInformation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] doc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public string PageRange;
        
        public ExportToTiffWithRangeRequest()
        {
        }
        
        public ExportToTiffWithRangeRequest(RepGen96.AuthenticationInformation AuthenticationInformation, byte[] doc, string PageRange)
        {
            this.AuthenticationInformation = AuthenticationInformation;
            this.doc = doc;
            this.PageRange = PageRange;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToTiffWithRangeResponse", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToTiffWithRangeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ExportToTiffWithRangeResult;
        
        public ExportToTiffWithRangeResponse()
        {
        }
        
        public ExportToTiffWithRangeResponse(byte[] ExportToTiffWithRangeResult)
        {
            this.ExportToTiffWithRangeResult = ExportToTiffWithRangeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToTxt", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToTxtRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.praceng.com/webservices/perepgen")]
        public RepGen96.AuthenticationInformation AuthenticationInformation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] doc;
        
        public ExportToTxtRequest()
        {
        }
        
        public ExportToTxtRequest(RepGen96.AuthenticationInformation AuthenticationInformation, byte[] doc)
        {
            this.AuthenticationInformation = AuthenticationInformation;
            this.doc = doc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToTxtResponse", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToTxtResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ExportToTxtResult;
        
        public ExportToTxtResponse()
        {
        }
        
        public ExportToTxtResponse(byte[] ExportToTxtResult)
        {
            this.ExportToTxtResult = ExportToTxtResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToTxtWithRange", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToTxtWithRangeRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.praceng.com/webservices/perepgen")]
        public RepGen96.AuthenticationInformation AuthenticationInformation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] doc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public string PageRange;
        
        public ExportToTxtWithRangeRequest()
        {
        }
        
        public ExportToTxtWithRangeRequest(RepGen96.AuthenticationInformation AuthenticationInformation, byte[] doc, string PageRange)
        {
            this.AuthenticationInformation = AuthenticationInformation;
            this.doc = doc;
            this.PageRange = PageRange;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToTxtWithRangeResponse", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToTxtWithRangeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ExportToTxtWithRangeResult;
        
        public ExportToTxtWithRangeResponse()
        {
        }
        
        public ExportToTxtWithRangeResponse(byte[] ExportToTxtWithRangeResult)
        {
            this.ExportToTxtWithRangeResult = ExportToTxtWithRangeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PrintGrid", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class PrintGridRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.praceng.com/webservices/perepgen")]
        public RepGen96.AuthenticationInformation AuthenticationInformation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        public object[] theColumns;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public decimal GridWidth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=2)]
        public RepGen96.ArrayOfXElement ds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=3)]
        public string Title;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=4)]
        public bool Paging;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=5)]
        public string Language;
        
        public PrintGridRequest()
        {
        }
        
        public PrintGridRequest(RepGen96.AuthenticationInformation AuthenticationInformation, object[] theColumns, decimal GridWidth, RepGen96.ArrayOfXElement ds, string Title, bool Paging, string Language)
        {
            this.AuthenticationInformation = AuthenticationInformation;
            this.theColumns = theColumns;
            this.GridWidth = GridWidth;
            this.ds = ds;
            this.Title = Title;
            this.Paging = Paging;
            this.Language = Language;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PrintGridResponse", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class PrintGridResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] PrintGridResult;
        
        public PrintGridResponse()
        {
        }
        
        public PrintGridResponse(byte[] PrintGridResult)
        {
            this.PrintGridResult = PrintGridResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface PERepGenSoapChannel : RepGen96.PERepGenSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class PERepGenSoapClient : System.ServiceModel.ClientBase<RepGen96.PERepGenSoap>, RepGen96.PERepGenSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PERepGenSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(PERepGenSoapClient.GetBindingForEndpoint(endpointConfiguration), PERepGenSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PERepGenSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PERepGenSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PERepGenSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PERepGenSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PERepGenSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<RepGen96.GenerateFeeResponse> GenerateFeeAsync(RepGen96.GenerateFeeRequest request)
        {
            return base.Channel.GenerateFeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepGen96.GenerateStatementResponse> GenerateStatementAsync(RepGen96.GenerateStatementRequest request)
        {
            return base.Channel.GenerateStatementAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepGen96.GenerateExpenseReportResponse> GenerateExpenseReportAsync(RepGen96.GenerateExpenseReportRequest request)
        {
            return base.Channel.GenerateExpenseReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepGen96.GenerateAndStoreReportResponse> GenerateAndStoreReportAsync(RepGen96.GenerateAndStoreReportRequest request)
        {
            return base.Channel.GenerateAndStoreReportAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepGen96.GetThumbnailForReportResponse> RepGen96.PERepGenSoap.GetThumbnailForReportAsync(RepGen96.GetThumbnailForReportRequest request)
        {
            return base.Channel.GetThumbnailForReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepGen96.GetThumbnailForReportResponse> GetThumbnailForReportAsync(RepGen96.AuthenticationInformation AuthenticationInformation, System.Guid fileID)
        {
            RepGen96.GetThumbnailForReportRequest inValue = new RepGen96.GetThumbnailForReportRequest();
            inValue.AuthenticationInformation = AuthenticationInformation;
            inValue.fileID = fileID;
            return ((RepGen96.PERepGenSoap)(this)).GetThumbnailForReportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepGen96.ExportReportResponse> RepGen96.PERepGenSoap.ExportReportAsync(RepGen96.ExportReportRequest request)
        {
            return base.Channel.ExportReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepGen96.ExportReportResponse> ExportReportAsync(RepGen96.AuthenticationInformation AuthenticationInformation, System.Guid fileID, string exportType, int firstPage, int lastPage)
        {
            RepGen96.ExportReportRequest inValue = new RepGen96.ExportReportRequest();
            inValue.AuthenticationInformation = AuthenticationInformation;
            inValue.fileID = fileID;
            inValue.exportType = exportType;
            inValue.firstPage = firstPage;
            inValue.lastPage = lastPage;
            return ((RepGen96.PERepGenSoap)(this)).ExportReportAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<RepGen96.GenerateReportResponse> GenerateReportAsync(RepGen96.GenerateReportRequest request)
        {
            return base.Channel.GenerateReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepGen96.GenerateReportToPDFResponse> GenerateReportToPDFAsync(RepGen96.GenerateReportToPDFRequest request)
        {
            return base.Channel.GenerateReportToPDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepGen96.GenerateReportToPDFv9Response> GenerateReportToPDFv9Async(RepGen96.GenerateReportToPDFv9Request request)
        {
            return base.Channel.GenerateReportToPDFv9Async(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepGen96.ExportToExcelResponse> RepGen96.PERepGenSoap.ExportToExcelAsync(RepGen96.ExportToExcelRequest request)
        {
            return base.Channel.ExportToExcelAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepGen96.ExportToExcelResponse> ExportToExcelAsync(RepGen96.AuthenticationInformation AuthenticationInformation, byte[] doc)
        {
            RepGen96.ExportToExcelRequest inValue = new RepGen96.ExportToExcelRequest();
            inValue.AuthenticationInformation = AuthenticationInformation;
            inValue.doc = doc;
            return ((RepGen96.PERepGenSoap)(this)).ExportToExcelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepGen96.ExportToExcelWithRangeResponse> RepGen96.PERepGenSoap.ExportToExcelWithRangeAsync(RepGen96.ExportToExcelWithRangeRequest request)
        {
            return base.Channel.ExportToExcelWithRangeAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepGen96.ExportToExcelWithRangeResponse> ExportToExcelWithRangeAsync(RepGen96.AuthenticationInformation AuthenticationInformation, byte[] doc, string PageRange)
        {
            RepGen96.ExportToExcelWithRangeRequest inValue = new RepGen96.ExportToExcelWithRangeRequest();
            inValue.AuthenticationInformation = AuthenticationInformation;
            inValue.doc = doc;
            inValue.PageRange = PageRange;
            return ((RepGen96.PERepGenSoap)(this)).ExportToExcelWithRangeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepGen96.ExportToPDFResponse> RepGen96.PERepGenSoap.ExportToPDFAsync(RepGen96.ExportToPDFRequest request)
        {
            return base.Channel.ExportToPDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepGen96.ExportToPDFResponse> ExportToPDFAsync(RepGen96.AuthenticationInformation AuthenticationInformation, byte[] doc)
        {
            RepGen96.ExportToPDFRequest inValue = new RepGen96.ExportToPDFRequest();
            inValue.AuthenticationInformation = AuthenticationInformation;
            inValue.doc = doc;
            return ((RepGen96.PERepGenSoap)(this)).ExportToPDFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepGen96.ExportToPDFWithRangeResponse> RepGen96.PERepGenSoap.ExportToPDFWithRangeAsync(RepGen96.ExportToPDFWithRangeRequest request)
        {
            return base.Channel.ExportToPDFWithRangeAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepGen96.ExportToPDFWithRangeResponse> ExportToPDFWithRangeAsync(RepGen96.AuthenticationInformation AuthenticationInformation, byte[] doc, string PageRange)
        {
            RepGen96.ExportToPDFWithRangeRequest inValue = new RepGen96.ExportToPDFWithRangeRequest();
            inValue.AuthenticationInformation = AuthenticationInformation;
            inValue.doc = doc;
            inValue.PageRange = PageRange;
            return ((RepGen96.PERepGenSoap)(this)).ExportToPDFWithRangeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepGen96.ExportToWordResponse> RepGen96.PERepGenSoap.ExportToWordAsync(RepGen96.ExportToWordRequest request)
        {
            return base.Channel.ExportToWordAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepGen96.ExportToWordResponse> ExportToWordAsync(RepGen96.AuthenticationInformation AuthenticationInformation, byte[] doc)
        {
            RepGen96.ExportToWordRequest inValue = new RepGen96.ExportToWordRequest();
            inValue.AuthenticationInformation = AuthenticationInformation;
            inValue.doc = doc;
            return ((RepGen96.PERepGenSoap)(this)).ExportToWordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepGen96.ExportToWordWithRangeResponse> RepGen96.PERepGenSoap.ExportToWordWithRangeAsync(RepGen96.ExportToWordWithRangeRequest request)
        {
            return base.Channel.ExportToWordWithRangeAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepGen96.ExportToWordWithRangeResponse> ExportToWordWithRangeAsync(RepGen96.AuthenticationInformation AuthenticationInformation, byte[] doc, string PageRange)
        {
            RepGen96.ExportToWordWithRangeRequest inValue = new RepGen96.ExportToWordWithRangeRequest();
            inValue.AuthenticationInformation = AuthenticationInformation;
            inValue.doc = doc;
            inValue.PageRange = PageRange;
            return ((RepGen96.PERepGenSoap)(this)).ExportToWordWithRangeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepGen96.ExportToTiffResponse> RepGen96.PERepGenSoap.ExportToTiffAsync(RepGen96.ExportToTiffRequest request)
        {
            return base.Channel.ExportToTiffAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepGen96.ExportToTiffResponse> ExportToTiffAsync(RepGen96.AuthenticationInformation AuthenticationInformation, byte[] doc)
        {
            RepGen96.ExportToTiffRequest inValue = new RepGen96.ExportToTiffRequest();
            inValue.AuthenticationInformation = AuthenticationInformation;
            inValue.doc = doc;
            return ((RepGen96.PERepGenSoap)(this)).ExportToTiffAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepGen96.ExportToTiffWithRangeResponse> RepGen96.PERepGenSoap.ExportToTiffWithRangeAsync(RepGen96.ExportToTiffWithRangeRequest request)
        {
            return base.Channel.ExportToTiffWithRangeAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepGen96.ExportToTiffWithRangeResponse> ExportToTiffWithRangeAsync(RepGen96.AuthenticationInformation AuthenticationInformation, byte[] doc, string PageRange)
        {
            RepGen96.ExportToTiffWithRangeRequest inValue = new RepGen96.ExportToTiffWithRangeRequest();
            inValue.AuthenticationInformation = AuthenticationInformation;
            inValue.doc = doc;
            inValue.PageRange = PageRange;
            return ((RepGen96.PERepGenSoap)(this)).ExportToTiffWithRangeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepGen96.ExportToTxtResponse> RepGen96.PERepGenSoap.ExportToTxtAsync(RepGen96.ExportToTxtRequest request)
        {
            return base.Channel.ExportToTxtAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepGen96.ExportToTxtResponse> ExportToTxtAsync(RepGen96.AuthenticationInformation AuthenticationInformation, byte[] doc)
        {
            RepGen96.ExportToTxtRequest inValue = new RepGen96.ExportToTxtRequest();
            inValue.AuthenticationInformation = AuthenticationInformation;
            inValue.doc = doc;
            return ((RepGen96.PERepGenSoap)(this)).ExportToTxtAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepGen96.ExportToTxtWithRangeResponse> RepGen96.PERepGenSoap.ExportToTxtWithRangeAsync(RepGen96.ExportToTxtWithRangeRequest request)
        {
            return base.Channel.ExportToTxtWithRangeAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepGen96.ExportToTxtWithRangeResponse> ExportToTxtWithRangeAsync(RepGen96.AuthenticationInformation AuthenticationInformation, byte[] doc, string PageRange)
        {
            RepGen96.ExportToTxtWithRangeRequest inValue = new RepGen96.ExportToTxtWithRangeRequest();
            inValue.AuthenticationInformation = AuthenticationInformation;
            inValue.doc = doc;
            inValue.PageRange = PageRange;
            return ((RepGen96.PERepGenSoap)(this)).ExportToTxtWithRangeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepGen96.PrintGridResponse> RepGen96.PERepGenSoap.PrintGridAsync(RepGen96.PrintGridRequest request)
        {
            return base.Channel.PrintGridAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepGen96.PrintGridResponse> PrintGridAsync(RepGen96.AuthenticationInformation AuthenticationInformation, object[] theColumns, decimal GridWidth, RepGen96.ArrayOfXElement ds, string Title, bool Paging, string Language)
        {
            RepGen96.PrintGridRequest inValue = new RepGen96.PrintGridRequest();
            inValue.AuthenticationInformation = AuthenticationInformation;
            inValue.theColumns = theColumns;
            inValue.GridWidth = GridWidth;
            inValue.ds = ds;
            inValue.Title = Title;
            inValue.Paging = Paging;
            inValue.Language = Language;
            return ((RepGen96.PERepGenSoap)(this)).PrintGridAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<string> TestMethodAsync(string Paramater)
        {
            return base.Channel.TestMethodAsync(Paramater);
        }
        
        public System.Threading.Tasks.Task<string> UploadReportLayoutsAsync()
        {
            return base.Channel.UploadReportLayoutsAsync();
        }
        
        public System.Threading.Tasks.Task<string> DownloadReportLayoutsAsync()
        {
            return base.Channel.DownloadReportLayoutsAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PERepGenSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.PERepGenSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PERepGenSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://pe-96.praceng.us/Reports/PERepGen.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.PERepGenSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://pe-96.praceng.us/Reports/PERepGen.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            PERepGenSoap,
            
            PERepGenSoap12,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
