//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepGen95
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.praceng.com/webservices/perepgen", ConfigurationName="RepGen95.PERepGenSoap")]
    public interface PERepGenSoap
    {
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/GenerateFee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RepGen95.GenerateFeeResponse> GenerateFeeAsync(RepGen95.GenerateFeeRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/GenerateStatement", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RepGen95.GenerateStatementResponse> GenerateStatementAsync(RepGen95.GenerateStatementRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/GenerateExpenseReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RepGen95.GenerateExpenseReportResponse> GenerateExpenseReportAsync(RepGen95.GenerateExpenseReportRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/GenerateAndStoreReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<RepGen95.GenerateAndStoreReportResponse> GenerateAndStoreReportAsync(RepGen95.GenerateAndStoreReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/GetThumbnailForReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<string> GetThumbnailForReportAsync(System.Guid fileID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/ExportReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<int> ExportReportAsync(System.Guid fileID, string exportType, int firstPage, int lastPage);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/GenerateReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<RepGen95.GenerateReportResponse> GenerateReportAsync(RepGen95.GenerateReportRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/GenerateReportToPDF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<RepGen95.GenerateReportToPDFResponse> GenerateReportToPDFAsync(RepGen95.GenerateReportToPDFRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/GenerateReportToPDFv9", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<RepGen95.GenerateReportToPDFv9Response> GenerateReportToPDFv9Async(RepGen95.GenerateReportToPDFv9Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/ExportToExcel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<RepGen95.ExportToExcelResponse> ExportToExcelAsync(RepGen95.ExportToExcelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/ExportToExcelWithRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<RepGen95.ExportToExcelWithRangeResponse> ExportToExcelWithRangeAsync(RepGen95.ExportToExcelWithRangeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/ExportToPDF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<RepGen95.ExportToPDFResponse> ExportToPDFAsync(RepGen95.ExportToPDFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/ExportToPDFWithRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<RepGen95.ExportToPDFWithRangeResponse> ExportToPDFWithRangeAsync(RepGen95.ExportToPDFWithRangeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/ExportToWord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<RepGen95.ExportToWordResponse> ExportToWordAsync(RepGen95.ExportToWordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/ExportToWordWithRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<RepGen95.ExportToWordWithRangeResponse> ExportToWordWithRangeAsync(RepGen95.ExportToWordWithRangeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/ExportToTiff", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<RepGen95.ExportToTiffResponse> ExportToTiffAsync(RepGen95.ExportToTiffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/ExportToTiffWithRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<RepGen95.ExportToTiffWithRangeResponse> ExportToTiffWithRangeAsync(RepGen95.ExportToTiffWithRangeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/ExportToTxt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<RepGen95.ExportToTxtResponse> ExportToTxtAsync(RepGen95.ExportToTxtRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/ExportToTxtWithRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<RepGen95.ExportToTxtWithRangeResponse> ExportToTxtWithRangeAsync(RepGen95.ExportToTxtWithRangeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/PrintGrid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<RepGen95.PrintGridResponse> PrintGridAsync(RepGen95.PrintGridRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/TestMethod", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<string> TestMethodAsync(string Paramater);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/UploadReportLayouts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<string> UploadReportLayoutsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praceng.com/webservices/perepgen/DownloadReportLayouts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<string> DownloadReportLayoutsAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateFee", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class GenerateFeeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        public int DebtTranIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public int Format;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=2)]
        public int StaffId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=3)]
        public string Error;
        
        public GenerateFeeRequest()
        {
        }
        
        public GenerateFeeRequest(int DebtTranIndex, int Format, int StaffId, string Error)
        {
            this.DebtTranIndex = DebtTranIndex;
            this.Format = Format;
            this.StaffId = StaffId;
            this.Error = Error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateFeeResponse", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class GenerateFeeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GenerateFeeResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public string Error;
        
        public GenerateFeeResponse()
        {
        }
        
        public GenerateFeeResponse(byte[] GenerateFeeResult, string Error)
        {
            this.GenerateFeeResult = GenerateFeeResult;
            this.Error = Error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateStatement", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class GenerateStatementRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        public int ContIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public int Format;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=2)]
        public bool IncludeFees;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=3)]
        public int StaffId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=4)]
        public string Error;
        
        public GenerateStatementRequest()
        {
        }
        
        public GenerateStatementRequest(int ContIndex, int Format, bool IncludeFees, int StaffId, string Error)
        {
            this.ContIndex = ContIndex;
            this.Format = Format;
            this.IncludeFees = IncludeFees;
            this.StaffId = StaffId;
            this.Error = Error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateStatementResponse", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class GenerateStatementResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GenerateStatementResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public string Error;
        
        public GenerateStatementResponse()
        {
        }
        
        public GenerateStatementResponse(byte[] GenerateStatementResult, string Error)
        {
            this.GenerateStatementResult = GenerateStatementResult;
            this.Error = Error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateExpenseReport", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class GenerateExpenseReportRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        public int ExpIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public int StaffId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=2)]
        public string Error;
        
        public GenerateExpenseReportRequest()
        {
        }
        
        public GenerateExpenseReportRequest(int ExpIndex, int StaffId, string Error)
        {
            this.ExpIndex = ExpIndex;
            this.StaffId = StaffId;
            this.Error = Error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateExpenseReportResponse", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class GenerateExpenseReportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GenerateExpenseReportResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public string Error;
        
        public GenerateExpenseReportResponse()
        {
        }
        
        public GenerateExpenseReportResponse(byte[] GenerateExpenseReportResult, string Error)
        {
            this.GenerateExpenseReportResult = GenerateExpenseReportResult;
            this.Error = Error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateAndStoreReport", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class GenerateAndStoreReportRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        public string ReportID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public object[] Params;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=2)]
        public string StaffName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=3)]
        public string StaffId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=4)]
        public bool ErrorOnNoData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=5)]
        public string Error;
        
        public GenerateAndStoreReportRequest()
        {
        }
        
        public GenerateAndStoreReportRequest(string ReportID, object[] Params, string StaffName, string StaffId, bool ErrorOnNoData, string Error)
        {
            this.ReportID = ReportID;
            this.Params = Params;
            this.StaffName = StaffName;
            this.StaffId = StaffId;
            this.ErrorOnNoData = ErrorOnNoData;
            this.Error = Error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateAndStoreReportResponse", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class GenerateAndStoreReportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        public System.Guid GenerateAndStoreReportResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public string Error;
        
        public GenerateAndStoreReportResponse()
        {
        }
        
        public GenerateAndStoreReportResponse(System.Guid GenerateAndStoreReportResult, string Error)
        {
            this.GenerateAndStoreReportResult = GenerateAndStoreReportResult;
            this.Error = Error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateReport", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class GenerateReportRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        public string ReportID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public object[] Params;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=2)]
        public string StaffName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=3)]
        public string StaffId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=4)]
        public bool ErrorOnNoData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=5)]
        public string Error;
        
        public GenerateReportRequest()
        {
        }
        
        public GenerateReportRequest(string ReportID, object[] Params, string StaffName, string StaffId, bool ErrorOnNoData, string Error)
        {
            this.ReportID = ReportID;
            this.Params = Params;
            this.StaffName = StaffName;
            this.StaffId = StaffId;
            this.ErrorOnNoData = ErrorOnNoData;
            this.Error = Error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateReportResponse", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class GenerateReportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GenerateReportResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public string Error;
        
        public GenerateReportResponse()
        {
        }
        
        public GenerateReportResponse(byte[] GenerateReportResult, string Error)
        {
            this.GenerateReportResult = GenerateReportResult;
            this.Error = Error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateReportToPDF", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class GenerateReportToPDFRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        public string ReportID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public object[] Params;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=2)]
        public string StaffName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=3)]
        public string StaffId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=4)]
        public bool ErrorOnNoData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=5)]
        public string Error;
        
        public GenerateReportToPDFRequest()
        {
        }
        
        public GenerateReportToPDFRequest(string ReportID, object[] Params, string StaffName, string StaffId, bool ErrorOnNoData, string Error)
        {
            this.ReportID = ReportID;
            this.Params = Params;
            this.StaffName = StaffName;
            this.StaffId = StaffId;
            this.ErrorOnNoData = ErrorOnNoData;
            this.Error = Error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateReportToPDFResponse", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class GenerateReportToPDFResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GenerateReportToPDFResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public string Error;
        
        public GenerateReportToPDFResponse()
        {
        }
        
        public GenerateReportToPDFResponse(byte[] GenerateReportToPDFResult, string Error)
        {
            this.GenerateReportToPDFResult = GenerateReportToPDFResult;
            this.Error = Error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateReportToPDFv9", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class GenerateReportToPDFv9Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        public string ReportID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public object[] Params;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=2)]
        public string StaffName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=3)]
        public string StaffId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=4)]
        public bool ErrorOnNoData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=5)]
        public string Error;
        
        public GenerateReportToPDFv9Request()
        {
        }
        
        public GenerateReportToPDFv9Request(string ReportID, object[] Params, string StaffName, string StaffId, bool ErrorOnNoData, string Error)
        {
            this.ReportID = ReportID;
            this.Params = Params;
            this.StaffName = StaffName;
            this.StaffId = StaffId;
            this.ErrorOnNoData = ErrorOnNoData;
            this.Error = Error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateReportToPDFv9Response", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class GenerateReportToPDFv9Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GenerateReportToPDFv9Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public string Error;
        
        public GenerateReportToPDFv9Response()
        {
        }
        
        public GenerateReportToPDFv9Response(byte[] GenerateReportToPDFv9Result, string Error)
        {
            this.GenerateReportToPDFv9Result = GenerateReportToPDFv9Result;
            this.Error = Error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToExcel", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToExcelRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] doc;
        
        public ExportToExcelRequest()
        {
        }
        
        public ExportToExcelRequest(byte[] doc)
        {
            this.doc = doc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToExcelResponse", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToExcelResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ExportToExcelResult;
        
        public ExportToExcelResponse()
        {
        }
        
        public ExportToExcelResponse(byte[] ExportToExcelResult)
        {
            this.ExportToExcelResult = ExportToExcelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToExcelWithRange", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToExcelWithRangeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] doc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public string PageRange;
        
        public ExportToExcelWithRangeRequest()
        {
        }
        
        public ExportToExcelWithRangeRequest(byte[] doc, string PageRange)
        {
            this.doc = doc;
            this.PageRange = PageRange;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToExcelWithRangeResponse", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToExcelWithRangeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ExportToExcelWithRangeResult;
        
        public ExportToExcelWithRangeResponse()
        {
        }
        
        public ExportToExcelWithRangeResponse(byte[] ExportToExcelWithRangeResult)
        {
            this.ExportToExcelWithRangeResult = ExportToExcelWithRangeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToPDF", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToPDFRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] doc;
        
        public ExportToPDFRequest()
        {
        }
        
        public ExportToPDFRequest(byte[] doc)
        {
            this.doc = doc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToPDFResponse", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToPDFResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ExportToPDFResult;
        
        public ExportToPDFResponse()
        {
        }
        
        public ExportToPDFResponse(byte[] ExportToPDFResult)
        {
            this.ExportToPDFResult = ExportToPDFResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToPDFWithRange", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToPDFWithRangeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] doc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public string PageRange;
        
        public ExportToPDFWithRangeRequest()
        {
        }
        
        public ExportToPDFWithRangeRequest(byte[] doc, string PageRange)
        {
            this.doc = doc;
            this.PageRange = PageRange;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToPDFWithRangeResponse", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToPDFWithRangeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ExportToPDFWithRangeResult;
        
        public ExportToPDFWithRangeResponse()
        {
        }
        
        public ExportToPDFWithRangeResponse(byte[] ExportToPDFWithRangeResult)
        {
            this.ExportToPDFWithRangeResult = ExportToPDFWithRangeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToWord", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToWordRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] doc;
        
        public ExportToWordRequest()
        {
        }
        
        public ExportToWordRequest(byte[] doc)
        {
            this.doc = doc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToWordResponse", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToWordResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ExportToWordResult;
        
        public ExportToWordResponse()
        {
        }
        
        public ExportToWordResponse(byte[] ExportToWordResult)
        {
            this.ExportToWordResult = ExportToWordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToWordWithRange", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToWordWithRangeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] doc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public string PageRange;
        
        public ExportToWordWithRangeRequest()
        {
        }
        
        public ExportToWordWithRangeRequest(byte[] doc, string PageRange)
        {
            this.doc = doc;
            this.PageRange = PageRange;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToWordWithRangeResponse", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToWordWithRangeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ExportToWordWithRangeResult;
        
        public ExportToWordWithRangeResponse()
        {
        }
        
        public ExportToWordWithRangeResponse(byte[] ExportToWordWithRangeResult)
        {
            this.ExportToWordWithRangeResult = ExportToWordWithRangeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToTiff", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToTiffRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] doc;
        
        public ExportToTiffRequest()
        {
        }
        
        public ExportToTiffRequest(byte[] doc)
        {
            this.doc = doc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToTiffResponse", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToTiffResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ExportToTiffResult;
        
        public ExportToTiffResponse()
        {
        }
        
        public ExportToTiffResponse(byte[] ExportToTiffResult)
        {
            this.ExportToTiffResult = ExportToTiffResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToTiffWithRange", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToTiffWithRangeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] doc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public string PageRange;
        
        public ExportToTiffWithRangeRequest()
        {
        }
        
        public ExportToTiffWithRangeRequest(byte[] doc, string PageRange)
        {
            this.doc = doc;
            this.PageRange = PageRange;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToTiffWithRangeResponse", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToTiffWithRangeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ExportToTiffWithRangeResult;
        
        public ExportToTiffWithRangeResponse()
        {
        }
        
        public ExportToTiffWithRangeResponse(byte[] ExportToTiffWithRangeResult)
        {
            this.ExportToTiffWithRangeResult = ExportToTiffWithRangeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToTxt", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToTxtRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] doc;
        
        public ExportToTxtRequest()
        {
        }
        
        public ExportToTxtRequest(byte[] doc)
        {
            this.doc = doc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToTxtResponse", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToTxtResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ExportToTxtResult;
        
        public ExportToTxtResponse()
        {
        }
        
        public ExportToTxtResponse(byte[] ExportToTxtResult)
        {
            this.ExportToTxtResult = ExportToTxtResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToTxtWithRange", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToTxtWithRangeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] doc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public string PageRange;
        
        public ExportToTxtWithRangeRequest()
        {
        }
        
        public ExportToTxtWithRangeRequest(byte[] doc, string PageRange)
        {
            this.doc = doc;
            this.PageRange = PageRange;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToTxtWithRangeResponse", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class ExportToTxtWithRangeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ExportToTxtWithRangeResult;
        
        public ExportToTxtWithRangeResponse()
        {
        }
        
        public ExportToTxtWithRangeResponse(byte[] ExportToTxtWithRangeResult)
        {
            this.ExportToTxtWithRangeResult = ExportToTxtWithRangeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PrintGrid", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class PrintGridRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        public object[] theColumns;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=1)]
        public decimal GridWidth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=2)]
        public RepGen95.ArrayOfXElement ds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=3)]
        public string Title;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=4)]
        public bool Paging;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=5)]
        public string Language;
        
        public PrintGridRequest()
        {
        }
        
        public PrintGridRequest(object[] theColumns, decimal GridWidth, RepGen95.ArrayOfXElement ds, string Title, bool Paging, string Language)
        {
            this.theColumns = theColumns;
            this.GridWidth = GridWidth;
            this.ds = ds;
            this.Title = Title;
            this.Paging = Paging;
            this.Language = Language;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PrintGridResponse", WrapperNamespace="http://www.praceng.com/webservices/perepgen", IsWrapped=true)]
    public partial class PrintGridResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praceng.com/webservices/perepgen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] PrintGridResult;
        
        public PrintGridResponse()
        {
        }
        
        public PrintGridResponse(byte[] PrintGridResult)
        {
            this.PrintGridResult = PrintGridResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface PERepGenSoapChannel : RepGen95.PERepGenSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class PERepGenSoapClient : System.ServiceModel.ClientBase<RepGen95.PERepGenSoap>, RepGen95.PERepGenSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PERepGenSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(PERepGenSoapClient.GetBindingForEndpoint(endpointConfiguration), PERepGenSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PERepGenSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PERepGenSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PERepGenSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PERepGenSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PERepGenSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<RepGen95.GenerateFeeResponse> GenerateFeeAsync(RepGen95.GenerateFeeRequest request)
        {
            return base.Channel.GenerateFeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepGen95.GenerateStatementResponse> GenerateStatementAsync(RepGen95.GenerateStatementRequest request)
        {
            return base.Channel.GenerateStatementAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepGen95.GenerateExpenseReportResponse> GenerateExpenseReportAsync(RepGen95.GenerateExpenseReportRequest request)
        {
            return base.Channel.GenerateExpenseReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepGen95.GenerateAndStoreReportResponse> GenerateAndStoreReportAsync(RepGen95.GenerateAndStoreReportRequest request)
        {
            return base.Channel.GenerateAndStoreReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<string> GetThumbnailForReportAsync(System.Guid fileID)
        {
            return base.Channel.GetThumbnailForReportAsync(fileID);
        }
        
        public System.Threading.Tasks.Task<int> ExportReportAsync(System.Guid fileID, string exportType, int firstPage, int lastPage)
        {
            return base.Channel.ExportReportAsync(fileID, exportType, firstPage, lastPage);
        }
        
        public System.Threading.Tasks.Task<RepGen95.GenerateReportResponse> GenerateReportAsync(RepGen95.GenerateReportRequest request)
        {
            return base.Channel.GenerateReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepGen95.GenerateReportToPDFResponse> GenerateReportToPDFAsync(RepGen95.GenerateReportToPDFRequest request)
        {
            return base.Channel.GenerateReportToPDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepGen95.GenerateReportToPDFv9Response> GenerateReportToPDFv9Async(RepGen95.GenerateReportToPDFv9Request request)
        {
            return base.Channel.GenerateReportToPDFv9Async(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepGen95.ExportToExcelResponse> RepGen95.PERepGenSoap.ExportToExcelAsync(RepGen95.ExportToExcelRequest request)
        {
            return base.Channel.ExportToExcelAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepGen95.ExportToExcelResponse> ExportToExcelAsync(byte[] doc)
        {
            RepGen95.ExportToExcelRequest inValue = new RepGen95.ExportToExcelRequest();
            inValue.doc = doc;
            return ((RepGen95.PERepGenSoap)(this)).ExportToExcelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepGen95.ExportToExcelWithRangeResponse> RepGen95.PERepGenSoap.ExportToExcelWithRangeAsync(RepGen95.ExportToExcelWithRangeRequest request)
        {
            return base.Channel.ExportToExcelWithRangeAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepGen95.ExportToExcelWithRangeResponse> ExportToExcelWithRangeAsync(byte[] doc, string PageRange)
        {
            RepGen95.ExportToExcelWithRangeRequest inValue = new RepGen95.ExportToExcelWithRangeRequest();
            inValue.doc = doc;
            inValue.PageRange = PageRange;
            return ((RepGen95.PERepGenSoap)(this)).ExportToExcelWithRangeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepGen95.ExportToPDFResponse> RepGen95.PERepGenSoap.ExportToPDFAsync(RepGen95.ExportToPDFRequest request)
        {
            return base.Channel.ExportToPDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepGen95.ExportToPDFResponse> ExportToPDFAsync(byte[] doc)
        {
            RepGen95.ExportToPDFRequest inValue = new RepGen95.ExportToPDFRequest();
            inValue.doc = doc;
            return ((RepGen95.PERepGenSoap)(this)).ExportToPDFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepGen95.ExportToPDFWithRangeResponse> RepGen95.PERepGenSoap.ExportToPDFWithRangeAsync(RepGen95.ExportToPDFWithRangeRequest request)
        {
            return base.Channel.ExportToPDFWithRangeAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepGen95.ExportToPDFWithRangeResponse> ExportToPDFWithRangeAsync(byte[] doc, string PageRange)
        {
            RepGen95.ExportToPDFWithRangeRequest inValue = new RepGen95.ExportToPDFWithRangeRequest();
            inValue.doc = doc;
            inValue.PageRange = PageRange;
            return ((RepGen95.PERepGenSoap)(this)).ExportToPDFWithRangeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepGen95.ExportToWordResponse> RepGen95.PERepGenSoap.ExportToWordAsync(RepGen95.ExportToWordRequest request)
        {
            return base.Channel.ExportToWordAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepGen95.ExportToWordResponse> ExportToWordAsync(byte[] doc)
        {
            RepGen95.ExportToWordRequest inValue = new RepGen95.ExportToWordRequest();
            inValue.doc = doc;
            return ((RepGen95.PERepGenSoap)(this)).ExportToWordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepGen95.ExportToWordWithRangeResponse> RepGen95.PERepGenSoap.ExportToWordWithRangeAsync(RepGen95.ExportToWordWithRangeRequest request)
        {
            return base.Channel.ExportToWordWithRangeAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepGen95.ExportToWordWithRangeResponse> ExportToWordWithRangeAsync(byte[] doc, string PageRange)
        {
            RepGen95.ExportToWordWithRangeRequest inValue = new RepGen95.ExportToWordWithRangeRequest();
            inValue.doc = doc;
            inValue.PageRange = PageRange;
            return ((RepGen95.PERepGenSoap)(this)).ExportToWordWithRangeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepGen95.ExportToTiffResponse> RepGen95.PERepGenSoap.ExportToTiffAsync(RepGen95.ExportToTiffRequest request)
        {
            return base.Channel.ExportToTiffAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepGen95.ExportToTiffResponse> ExportToTiffAsync(byte[] doc)
        {
            RepGen95.ExportToTiffRequest inValue = new RepGen95.ExportToTiffRequest();
            inValue.doc = doc;
            return ((RepGen95.PERepGenSoap)(this)).ExportToTiffAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepGen95.ExportToTiffWithRangeResponse> RepGen95.PERepGenSoap.ExportToTiffWithRangeAsync(RepGen95.ExportToTiffWithRangeRequest request)
        {
            return base.Channel.ExportToTiffWithRangeAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepGen95.ExportToTiffWithRangeResponse> ExportToTiffWithRangeAsync(byte[] doc, string PageRange)
        {
            RepGen95.ExportToTiffWithRangeRequest inValue = new RepGen95.ExportToTiffWithRangeRequest();
            inValue.doc = doc;
            inValue.PageRange = PageRange;
            return ((RepGen95.PERepGenSoap)(this)).ExportToTiffWithRangeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepGen95.ExportToTxtResponse> RepGen95.PERepGenSoap.ExportToTxtAsync(RepGen95.ExportToTxtRequest request)
        {
            return base.Channel.ExportToTxtAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepGen95.ExportToTxtResponse> ExportToTxtAsync(byte[] doc)
        {
            RepGen95.ExportToTxtRequest inValue = new RepGen95.ExportToTxtRequest();
            inValue.doc = doc;
            return ((RepGen95.PERepGenSoap)(this)).ExportToTxtAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepGen95.ExportToTxtWithRangeResponse> RepGen95.PERepGenSoap.ExportToTxtWithRangeAsync(RepGen95.ExportToTxtWithRangeRequest request)
        {
            return base.Channel.ExportToTxtWithRangeAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepGen95.ExportToTxtWithRangeResponse> ExportToTxtWithRangeAsync(byte[] doc, string PageRange)
        {
            RepGen95.ExportToTxtWithRangeRequest inValue = new RepGen95.ExportToTxtWithRangeRequest();
            inValue.doc = doc;
            inValue.PageRange = PageRange;
            return ((RepGen95.PERepGenSoap)(this)).ExportToTxtWithRangeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepGen95.PrintGridResponse> RepGen95.PERepGenSoap.PrintGridAsync(RepGen95.PrintGridRequest request)
        {
            return base.Channel.PrintGridAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepGen95.PrintGridResponse> PrintGridAsync(object[] theColumns, decimal GridWidth, RepGen95.ArrayOfXElement ds, string Title, bool Paging, string Language)
        {
            RepGen95.PrintGridRequest inValue = new RepGen95.PrintGridRequest();
            inValue.theColumns = theColumns;
            inValue.GridWidth = GridWidth;
            inValue.ds = ds;
            inValue.Title = Title;
            inValue.Paging = Paging;
            inValue.Language = Language;
            return ((RepGen95.PERepGenSoap)(this)).PrintGridAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<string> TestMethodAsync(string Paramater)
        {
            return base.Channel.TestMethodAsync(Paramater);
        }
        
        public System.Threading.Tasks.Task<string> UploadReportLayoutsAsync()
        {
            return base.Channel.UploadReportLayoutsAsync();
        }
        
        public System.Threading.Tasks.Task<string> DownloadReportLayoutsAsync()
        {
            return base.Channel.DownloadReportLayoutsAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PERepGenSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.PERepGenSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PERepGenSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://pe-95.praceng.us/Reports/PERepGen.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.PERepGenSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://pe-95.praceng.us/Reports/PERepGen.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            PERepGenSoap,
            
            PERepGenSoap12,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
